behaviors:
  EscapeRoom:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
    batch_size: 64
    buffer_size: 2048
    learning_rate: 3.0e-4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
